In [1]:
import torch
import numpy as np

## Torch Tensor & Numy Bridge

In [2]:
print(torch.tensor([5.5, 3]))
print(torch.rand(2, 3))
print(torch.zeros(2, 3, dtype=torch.long))
print(torch.empty(2, 3))

tensor([5.5000, 3.0000])
tensor([[0.1478, 0.7989, 0.6090],
        [0.1093, 0.9381, 0.7433]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[ 0.0000e+00, -2.0000e+00,  2.3805e+11],
        [ 8.5920e+09,  4.0419e-16,  4.5880e-41]])


In [3]:
x = torch.tensor([5.5, 3])
x = x.new_ones(2, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.size())
m, n = x.size()
print(m, n)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8423,  1.8473, -0.5657],
        [ 0.7424, -0.1076, -0.0094]])
torch.Size([2, 3])
2 3


In [4]:
y = torch.rand(2, 3)
x = torch.rand(2, 3)
result = torch.empty(2, 3)
result = torch.add(x, y, out=result)
print(x,'\n', y, '\n', x+y, '\n', result)

tensor([[0.2314, 0.6082, 0.3992],
        [0.5058, 0.6662, 0.5075]]) 
 tensor([[0.1890, 0.3824, 0.1145],
        [0.6233, 0.3432, 0.6310]]) 
 tensor([[0.4205, 0.9906, 0.5137],
        [1.1290, 1.0094, 1.1385]]) 
 tensor([[0.4205, 0.9906, 0.5137],
        [1.1290, 1.0094, 1.1385]])


In [5]:
y.add_(x) # add x to y
print(y)  # check with result printing in previous box

tensor([[0.4205, 0.9906, 0.5137],
        [1.1290, 1.0094, 1.1385]])


In [6]:
x = torch.tensor([[1, 2, 3], [1, 2, 3]])
print(x[:, 0:2])

tensor([[1, 2],
        [1, 2]])


In [7]:
x = torch.randn(4, 4)
print(x.view(16).size())
print(x.view(-1, 8).size())

torch.Size([16])
torch.Size([2, 8])


In [8]:
np_data = np.arange(6).reshape(2, 3)
torch_data = torch.from_numpy(np_data)
np_data2 = torch_data.numpy()
print(np_data, '\n', torch_data, '\n', np_data2)

[[0 1 2]
 [3 4 5]] 
 tensor([[0, 1, 2],
        [3, 4, 5]]) 
 [[0 1 2]
 [3 4 5]]


## Autograd

Central to all neural networks in PyTorch is the autograd package. torch.Tensor is the central class of the package. 

*Tensor* “$o$”.
We have that   
$o = \frac{1}{4}\sum_i z_i$,  

$z_i = 3(x_i+2)^2$.  

$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$  

$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.

In [9]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


Printing variables, please note below terms:  
- rquires_grad
- grad_fn

In [11]:
print(x, '\n', y, '\n',z, '\n',out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) 
 tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) 
 tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) 
 tensor(27., grad_fn=<MeanBackward1>)


## Left over: Jacobian matrix  
Don't fully understand Jacobian Matrix and how it is used in pytorch. :-(